# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cb0a237cc7bb24f211addb4acceb097322b417005900ac5f3fa8597287e10a001c362466c8ea820f8967b7818bd0eb2d8ef75db5c45ca538ba68d5d13f5d0ea

test:
  secret_key_base: c399a768ef77ee076f2440a60bfa5281261878001a2a89bd820fb5a4ad23c46b24e621f1d1e40d55dc35a399e6f4043d0e5f17dcdcc308b939de3be274df5715

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
